### PR TITLE
Update strings-ro.xml

### PR DESCRIPTION
**Pull request by IulianSz**
Small corrections for romanian translation. 

I add and translate from english version some new strings.

### CODE REVIEW

**Comment by IulianSz** [comment]
I want to add and translate for existing english some new strings. Can i add it to strings-ro?

**Comment by IulianSz** [comment]
because i just found some new untranslated strings. new ones.

**Comment by creativetrendsapps** [comment]
In the RO translation?

**Comment by IulianSz** [comment]
yes, in ro

**Comment by IulianSz** [comment]
from strings.xml to strings-ro.xml

**Comment by IulianSz** [comment]
FAQ's for example is not in romanian at all....

**Comment by IulianSz** [comment]
Open links external also is not present

**Comment by IulianSz** [comment]
i mean there are some new strings that appear after i do the translation

**Comment by creativetrendsapps** [comment]
Sure, please don't overwrite the main strings.

**Comment by IulianSz** [comment]
no - i just add

**Comment by IulianSz** [comment]
and i want to ask you something...can i add myself to the translation list?

**Comment by IulianSz** [comment]
for romanian?

**Comment by creativetrendsapps** [comment]
Yes, but do it in the main strings.

**Comment by creativetrendsapps** [comment]
Also, yes there were new strings added after your translation. In the future all new English translations will be add to the bottom of any others. This way its easier to update.

**Comment by IulianSz** [comment]
ok!

**Pull request merged**
