### PR TITLE
Update strings-NL.xml

### PR DESCRIPTION
**Pull request by MrHappy**
Some tuning in translations, corrected some errors.

### CODE REVIEW

**Comment by creativetrendsapps** [comment]
Please sync these with the main branch. email me to get your promo code.

**Comment by MrHappy** [comment]
Am I missing something, but aren't these not already merged to the master branch?

Date: Sun, 31 Jan 2016 23:32:26 -0800

**Comment by creativetrendsapps** [comment]
This was a new pull request that I received., this wasn't in sync with my branch.

**Comment by MrHappy** [comment]
It has been merged with the master-branch, as has my later addition...
To which branched did it have to get merged?

**Pull request merged**
