### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by IulianSz**
Hi again.
I do the translation for the bottom part of file (i don't see it at the first check). I leave untranslated the Credit part only. I hope this will be ok.

Best
Iulian

### CODE REVIEW

**Comment by IulianSz** [comment]
Hi there.
Something strange is happening after last update, only with mobile data
active and used. Application shows free data version of the facebook site,
not the mobile one. I check and if i switch to wifi Folio shoes mobile
version.

So, i think is usefull a switch for fircing mobile version, like Tinfoil
had.

Or you have another option?

Best!
Iulian.

**Comment by RobertBoes** [comment]
I noticed the same, it loads 0.Facebook.com instead of the regular m.facebook.com

**Comment by creativetrendsapps** [comment]
Yes I'm aware of the issue. It was resolved on my end. Just waiting for Google to release it to everyone. I'll add a new section for apks here.

**Comment by IulianSz** [comment]
Issue solved. I just update and it works ok now.

**Pull request merged**
